Convert Wisconsin to use cms.cern.ch repository.

diff --git a/parrot_setup b/parrot_setup
--- a/parrot_setup
+++ b/parrot_setup
@@ -112,6 +112,13 @@ export PARROT_CVMFS_REPO
 echo "export PARROT_CVMFS_REPO=\"${PARROT_CVMFS_REPO}\"" > $GLIDEIN_PARROT/setup.sh \
   || die WN_Resource "failed to create parrot/setup.sh"
 
+# Copy optional parrot options from parrot_cfg to the glidein config file
+if ! [ -z "$GLIDEIN_PARROT_OPTIONS" ]; then
+  echo "GLIDEIN_PARROT_OPTIONS=\"${GLIDEIN_PARROT_OPTIONS}\"" \
+    >> $GLIDEIN_PARROT/setup.sh \
+  || die WN_Resource "failed to append to parrot/setup.sh"
+fi
+
 if [ "$CVMFS_OSG_APP" != "" ]; then
   # add CVMFS_OSG_APP to the job wrapper environment
   add_config_line CVMFS_OSG_APP $CVMFS_OSG_APP
